name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"
  pull_request:
    paths-ignore:
      - .gitignore
      - LICENSE
      - "**.md"

env:
  VLC_HASH: c4ab31d5f0d5d0ba298706241d5b67ae49215935 # 3.0.17.2

jobs:
  actionlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run actionlint
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
  build-linux:
    runs-on: ubuntu-latest

    needs: [actionlint]

    steps:
      - uses: actions/checkout@v2
        with:
          repository: "videolan/vlc"
          ref: ${{ env.VLC_HASH }}
      - uses: actions/checkout@v2
        with:
          path: vlc-build
      - name: Install build tools
        run: |
          sudo sed -i.back -e "s/^# deb-src/deb-src/g" /etc/apt/sources.list
          sudo apt update -y
          sudo apt install \
            git g++ make libtool automake autopoint pkg-config flex bison lua5.2
          sudo apt build-dep vlc
      - name: Prepare
        run: |
          ./bootstrap
          git apply vlc-build/patches/*.patch
          mkdir -p build
      - name: Configure
        run: |
          ./configure \
            --prefix $PWD/build \
            --disable-archive \
            --disable-live555 \
            --disable-dc1394 \
            --disable-dv1394 \
            --disable-linsys \
            --disable-dvdread \
            --disable-dvdnav \
            --disable-bluray \
            --disable-opencv \
            --disable-smbclient \
            --disable-dsm \
            --disable-sftp \
            --disable-nfs \
            --disable-smb2 \
            --disable-v4l2 \
            --disable-decklink \
            --disable-vcd \
            --disable-libcddb \
            --disable-screen \
            --disable-vnc \
            --disable-freerdp \
            --disable-realrtsp \
            --disable-macosx-avfoundation \
            --disable-asdcp \
            --enable-dvbpsi \
            --disable-gme \
            --disable-sid \
            --disable-ogg \
            --disable-shout \
            --disable-matroska \
            --disable-mod \
            --disable-mpc \
            --disable-wma-fixed \
            --disable-shine \
            --disable-omxil \
            --disable-omxil-vout \
            --disable-rpi-omxil \
            --disable-crystalhd \
            --disable-mad \
            --disable-mpg123 \
            --disable-gst-decode \
            --disable-merge-ffmpeg \
            --enable-avcodec \
            --disable-libva \
            --disable-dxva2 \
            --disable-d3d11va \
            --enable-avformat \
            --enable-swscale \
            --disable-postproc \
            --disable-faad \
            --disable-aom \
            --disable-dav1d \
            --disable-vpx \
            --disable-twolame \
            --disable-fdkaac \
            --disable-a52 \
            --disable-dca \
            --disable-flac \
            --enable-libmpeg2 \
            --disable-vorbis \
            --disable-tremor \
            --disable-speex \
            --disable-opus \
            --disable-spatialaudio \
            --disable-theora \
            --disable-oggspots \
            --disable-daala \
            --disable-schroedinger \
            --disable-png \
            --disable-jpeg \
            --disable-bpg \
            --disable-x262 \
            --enable-x265 \
            --enable-x264 \
            --disable-x26410b \
            --disable-mfx \
            --disable-fluidsynth \
            --disable-fluidlite \
            --disable-zvbi \
            --disable-telx \
            --disable-libass \
            --enable-aribsub \
            --disable-aribb25 \
            --disable-kate \
            --disable-tiger \
            --disable-css \
            --disable-gles2 \
            --without-x \
            --disable-xcb \
            --disable-xvideo \
            --disable-vdpau \
            --disable-wayland \
            --disable-sdl-image \
            --disable-freetype \
            --disable-fribidi \
            --disable-harfbuzz \
            --disable-fontconfig \
            --disable-svg \
            --disable-svgdec \
            --disable-directx \
            --disable-aa \
            --disable-caca \
            --disable-kva \
            --disable-mmal \
            --disable-evas \
            --enable-pulse \
            --disable-alsa \
            --disable-oss \
            --disable-sndio \
            --disable-wasapi \
            --disable-jack \
            --disable-opensles \
            --disable-tizen-audio \
            --disable-samplerate \
            --disable-soxr \
            --disable-kai \
            --disable-chromaprint \
            --disable-chromecast \
            --disable-qt \
            --disable-skins2 \
            --disable-libtar \
            --disable-macosx \
            --disable-sparkle \
            --disable-minimal-macosx \
            --disable-ncurses \
            --disable-lirc \
            --disable-srt \
            --disable-goom \
            --disable-projectm \
            --disable-vsxu \
            --disable-avahi \
            --disable-udev \
            --disable-mtp \
            --disable-upnp \
            --disable-microdns \
            --enable-libxml2 \
            --disable-libgcrypt \
            --enable-gnutls \
            --disable-taglib \
            --disable-secret \
            --disable-kwallet \
            --disable-update-check \
            --disable-osx-notifications \
            --disable-notify \
            --enable-libplacebo \
            --disable-vlc
      - name: Build
        run: |
          export CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions \
                          -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security \
                          -fstack-clash-protection -fcf-protection"
          export CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
          export MAKEFLAGS="-j2"
          make
      - name: Packaging
        run: |
          make install
      - name: Check
        run: ls -la
        working-directory: ./build/lib
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-build
          path: |
            build/lib/libvlccore.so.9.0.0
            build/lib/libvlc.so.5.6.0
